services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    restart: on-failure
    volumes:
      - ./api:/app
    env_file:
      - ./.env
    ports:
      - 1597:1597
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db:
