FROM golang:1.22-alpine
RUN go install github.com/bokwoon95/wgo@latest
RUN go install github.com/swaggo/swag/cmd/swag@latest
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

EXPOSE 1597
CMD wgo -xdir ./cmd/docs swag init --parseDependency  --parseInternal --parseDepth 1 -q -d cmd -o ./cmd/docs :: go run ./cmd
